dist: trusty
language: php

php:
  - 7.2
  - 7.3
  - 7.4

# This triggers builds to run on the new TravisCI infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

## Cache composer
cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.2
      env: 'COMPOSER_FLAGS="--prefer-stable --prefer-lowest"'

before_script:
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist

script:
  - php vendor/bin/phpcs src/ tests/ -n
  - php vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
  - php vendor/bin/phpstan analyse ./src ./tests
  - php bin/php-cs-fixer.phar fix --dry-run --diff --diff-format=udiff
